#!/bin/bash

#Backup existing php.ini file
sudo cp /etc/php/7.4/apache2/php.ini /etc/php/7.4/apache2/php.ini.bak

# Update the php directivies required by ianseo
# upload_max_filesize = 256M
# post_max_size = 256M
# memory_limit = 1024M

sudo sed -i 's,^upload_max_filesize =.*$,upload_max_filesize = 256M,' /etc/php/7.4/apache2/php.ini
sudo sed -i 's,^post_max_size =.*$,post_max_size = 256M,' /etc/php/7.4/apache2/php.ini
sudo sed -i 's,^memory_limit =.*$,memory_limit = 1024M,' /etc/php/7.4/apache2/php.ini
sudo sed -i 's,^max_execution_time =.*$,max_execution_time = 120,' /etc/php/7.4/apache2/php.ini

## Sets up the apache conf and site virtual host files
sudo rm -r /var/www/html
sudo chmod -R a+wX /var/www/ianseo
sudo rm /var/www/ianseo/Common/config.inc.php

#Disable default apache site and clean up
sudo a2dissite 000-default
sudo rm /etc/apache2/sites-available/000-default.conf
sudo rm /etc/apache2/sites-available/default-ssl.conf

#Download ianseo virtual hosts file
sudo wget -N https://raw.githubusercontent.com/artfulbodger/ianseo-pi/master/os%20files/apache/ianseo.conf --directory-prefix /etc/apache2/sites-available
sudo chown root /etc/apache2/sites-available/ianseo.conf
sudo chgrp root /etc/apache2/sites-available/ianseo.conf
sudo a2ensite ianseo
sudo systemctl reload apache2

# Restart apache for new php config
sudo service apache2 reload